### ISSUE TITLE
Plans of adding more lifecycle events?

### ISSUE THREAD

**Issue by abhaysood** [googlecodelabs/android-lifecycles#11]
I was playing around with google maps `MapView` which needs a bunch of lifecycle events to be called manually on the view, like onLowMemory() and onSaveInstanceState().

Are there any plans to include such events in the library? Or is there a way to extend the library to suit our needs.

**Comment by JoseAlcerreca** [comment]
They're not strictly lifecycle events, so I don't think so. @yigit to confirm.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab. This sounds like a feature request - if you'd like you can open a feature request on the public issue tracker. Instructions for doing so are [here](https://developer.android.com/jetpack/docs/feedback#issues)
