### ISSUE TITLE
viewModelScope.launch inits on main thread

### ISSUE THREAD

**Issue by BulatMukhutdinov** [googlecodelabs/android-lifecycles#55]
I am using kotlin coroutines and lifecycle extensions for it, specifically viewModelScope. I also turned on StrictMode. When I call 
```
viewModelScope.launch {}
```
in viewModel I have an error
```
StrictMode ThreadPolicy violation. Caused by: android.os.strictmode.DiskReadViolation
```
Why viewModelScope uses disk read in initialization and how to init viewModelScope right (without strict mode violations)?

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

If you have questions about how to do something outside of the codelab scope with lifecycles, you can ask them on Stack Overflow using the [Stack Overflow android-architecture-lifecycle tag](https://stackoverflow.com/questions/tagged/android-architecture-lifecycle) or [one of the other Architecture Component tags](https://developer.android.com/jetpack/docs/feedback#ask-questions).

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
